build:
  maxIssues: 0

complexity:
  LongMethod:
    active: true
    threshold: 120
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 10
  TooManyFunctions:
    active: true
    thresholdInFiles: 30
    thresholdInObjects: 25
    thresholdInClasses: 40
  CyclomaticComplexMethod:
    active: true
    threshold: 60

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 140
  ReturnCount:
    active: true
    max: 8
  UnusedParameter:
    active: false
  UnusedPrivateMember:
    active: true

naming:
  FunctionNaming:
    active: true
  TopLevelPropertyNaming:
    active: true
  VariableNaming:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false

empty-blocks:
  EmptyFunctionBlock:
    active: false
